name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: docker/build-push-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ferras1/metadata_service
          tag_with_ref: true
          tag_with_sha: true
          dockerfile: ${{ github.workspace }}/metadata_service/Dockerfile
